//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component :IEntityObjectState
    {
        public Component()
        {
            this.ComponentItems = new HashSet<ComponentItem>();
            this.TerminalComponentRoles = new HashSet<TerminalComponentRole>();
        }
    
        public int Id { get; set; }
        public string ModelNo { get; set; }
        public int ComponentTypeId { get; set; }
        public int ManufactureId { get; set; }
        public string Details { get; set; }
    
        public virtual ComponentType ComponentType { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual ICollection<ComponentItem> ComponentItems { get; set; }
        public virtual ICollection<TerminalComponentRole> TerminalComponentRoles { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
