//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;

    public partial class AccountTerminal : IEntityObjectState
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public int TerminalId { get; set; }

        public virtual Account Account { get; set; }
        public virtual Terminal Terminal { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
