//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;

    public partial class ActiveMode : IEntityObjectState
    {
        public ActiveMode()
        {
            this.TerminalComponents = new HashSet<TerminalComponent>();
        }

        public int Id { get; set; }
        public int RoleId { get; set; }
        public Nullable<double> AlertValue { get; set; }
        public bool isForDisplay { get; set; }
        public string Details { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<TerminalComponent> TerminalComponents { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
