//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentItem:IEntityObjectState
    {
        public int Id { get; set; }
        public int ComponentId { get; set; }
        public string SerialNo { get; set; }
        public string IMEI { get; set; }
        public System.DateTime ManufacturedDate { get; set; }
    
        public virtual Component Component { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
