//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port:IEntityObjectState
    {
        public Port()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public int PortTypeId { get; set; }
        public byte PortNo { get; set; }
        public int PortDirection { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual PortType PortType { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
