//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountTerminal> AccountTerminals { get; set; }
        public virtual DbSet<ActiveMode> ActiveModes { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentItem> ComponentItems { get; set; }
        public virtual DbSet<ComponentType> ComponentTypes { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<Manufacture> Manufactures { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<PortType> PortTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Terminal> Terminals { get; set; }
        public virtual DbSet<TerminalComponent> TerminalComponents { get; set; }
        public virtual DbSet<TerminalItem> TerminalItems { get; set; }
        public virtual DbSet<UnitItem> UnitItems { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
    }
}
