//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;

    public partial class TerminalComponentRole : IEntityObjectState
    {
        public TerminalComponentRole()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public int TerminalId { get; set; }
        public int ComponentId { get; set; }
        public int RoleId { get; set; }
        public byte ItemSeqNo { get; set; }
        public bool IsForDisplay { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Component Component { get; set; }
        public virtual Role Role { get; set; }
        public virtual Terminal Terminal { get; set; }

        public EntityObjectState ObjectState { get; set; }
    }
}
