//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal:IEntityObjectState
    {
        public Terminal()
        {
            this.AccountTerminals = new HashSet<AccountTerminal>();
            this.TerminalComponents = new HashSet<TerminalComponent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsStandard { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<AccountTerminal> AccountTerminals { get; set; }
        public virtual ICollection<TerminalComponent> TerminalComponents { get; set; }
        public EntityObjectState ObjectState { get; set; }
    }
}
